def populate_db():
    if db(db.t_sustancias).isempty():
        db.t_sustancias.insert(f_nombre='Acetato de Etilo', f_cas='141-78-6', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Acetona', f_cas='67-64-1', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Ácido Antranílico', f_cas='118-92-3', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Ácido Clorhídrico', f_cas='7647-01-0', f_pureza='37', f_estado='2', f_control='1', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Ácido Fenilacético y sus sales', f_cas='103-82-2', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Comburente')
        db.t_sustancias.insert(f_nombre='Ácido Nítrico', f_cas='7697-37-2', f_pureza='5', f_estado='2', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Ácido Pícrico (trinitrofenol)', f_cas='88-89-1', f_pureza='3', f_estado='1', f_control='2', f_peligrosidad='Explosivo')
        db.t_sustancias.insert(f_nombre='Ácido Sulfúrico', f_cas='7664-93-9', f_pureza='97', f_estado='2', f_control='3', f_peligrosidad='Corrosivo')
        db.t_sustancias.insert(f_nombre='Aluminio en polvo', f_cas='7429-90-5', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Amoníaco Anhídrico', f_cas='7664-41-7', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Nocivo')
        db.t_sustancias.insert(f_nombre='Amoníaco en disolución acuosa', f_cas='001336-21-6', f_pureza='25', f_estado='2', f_control='1', f_peligrosidad='Corrosivo')
        db.t_sustancias.insert(f_nombre='Anhídrico acético', f_cas='108-24-7', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Azidas (de sodio)', f_cas='26628-22-8', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Benceno', f_cas='71-43-2', f_pureza='99', f_estado='2', f_control='2', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Butanona (metilcetona)', f_cas='78-93-3', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Carbonato de Sodio', f_cas='497-19-8', f_pureza='99', f_estado='1', f_control='1', f_peligrosidad='Corrosivo')
        db.t_sustancias.insert(f_nombre='Clorato de Potasio', f_cas='3811-04-9', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Comburente')
        db.t_sustancias.insert(f_nombre='Clorato de Sodio', f_cas='7775-09-9', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Comburente')
        db.t_sustancias.insert(f_nombre='Cloroformo', f_cas='67-66-3', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Nocivo')
        db.t_sustancias.insert(f_nombre='Diclorometano', f_cas='75-09-2', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Nocivo')
        db.t_sustancias.insert(f_nombre='Dinitrofenol', f_cas='51-28-5', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Nocivo')
        db.t_sustancias.insert(f_nombre='Dinitrotolueno', f_cas='606-20-2', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Nocivo')
        db.t_sustancias.insert(f_nombre='Etanol', f_cas='64-17-5', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Eter Etílico', f_cas='60-29-7', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Explosivo')
        db.t_sustancias.insert(f_nombre='Fósforo blanco', f_cas='7723-14-0', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Fulminato de Mercurio', f_cas='', f_pureza='', f_estado='', f_control='2', f_peligrosidad='N/A')
        db.t_sustancias.insert(f_nombre='Heptano', f_cas='142-82-5', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Hexano', f_cas='110-54-3', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Hidrogenocarbonato (Bicarbonato) de Sodio', f_cas='144-55-8', f_pureza='99', f_estado='1', f_control='1', f_peligrosidad='Irritante')
        db.t_sustancias.insert(f_nombre='Hipoclorito de calcio', f_cas='7778-54-3', f_pureza='68', f_estado='1', f_control='2', f_peligrosidad='Corrosivo')
        db.t_sustancias.insert(f_nombre='Hipoclorito de Sodio', f_cas='7681-52-9', f_pureza='', f_estado='2', f_control='2', f_peligrosidad='Corrosivo')
        db.t_sustancias.insert(f_nombre='Metanol', f_cas='67-56-1', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Nitrato de Amonio (salitre de chile)', f_cas='6484-52-2', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Explosivo')
        db.t_sustancias.insert(f_nombre='Nitrato de Bismuto', f_cas='7697-37-2', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Corrosivo')
        db.t_sustancias.insert(f_nombre='Nitrato de Calcio', f_cas='13477-34-4', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Nitrato de Plata', f_cas='7761-88-8', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Corrosivo')
        db.t_sustancias.insert(f_nombre='Nitrato de Plomo', f_cas='10099-74-8', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Nitrato de Potasio', f_cas='7757-79-1', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Comburente')
        db.t_sustancias.insert(f_nombre='Nitrato de Sodio', f_cas='7631-99-4', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Comburente')
        db.t_sustancias.insert(f_nombre='Nitrito de Sodio', f_cas='7632-00-0', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Comburente')
        db.t_sustancias.insert(f_nombre='Nitrobenceno', f_cas='98-95-3', f_pureza='99', f_estado='2', f_control='2', f_peligrosidad='Nocivo')
        db.t_sustancias.insert(f_nombre='Nitrocelulosa', f_cas='9004-70-0', f_pureza='12', f_estado='1', f_control='2', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Nitroglicerina', f_cas='55-63-0', f_pureza='1', f_estado='1', f_control='2', f_peligrosidad='Explosivo')
        db.t_sustancias.insert(f_nombre='Perclorato de Potasio', f_cas='7778-74-7', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Comburente')
        db.t_sustancias.insert(f_nombre='Perclorato de Sodio', f_cas='7601-89-0', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Comburente')
        db.t_sustancias.insert(f_nombre='Permanganato de Potasio', f_cas='7722-64-7', f_pureza='99', f_estado='1', f_control='3', f_peligrosidad='Comburente')
        db.t_sustancias.insert(f_nombre='Sesquicarbonato de Sodio', f_cas='6106-20-3', f_pureza='99', f_estado='1', f_control='1', f_peligrosidad='Corrosivo')
        db.t_sustancias.insert(f_nombre='Sulfato de Amonio', f_cas='7783-20-2', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Corrosivo')
        db.t_sustancias.insert(f_nombre='Sulfato de Magnesio', f_cas='7487-88-9', f_pureza='65', f_estado='1', f_control='2', f_peligrosidad='Irritante')
        db.t_sustancias.insert(f_nombre='Sulfuro de Potasio', f_cas='1312-73-8', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Tetrahidrofurano', f_cas='109-99-9', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Tolueno', f_cas='108-88-3', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Trinitrotolueno (TNT)', f_cas='118-96-7', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Explosivo')
        db.t_sustancias.insert(f_nombre='Urea', f_cas='57-13-6 ', f_pureza='', f_estado='1', f_control='2', f_peligrosidad='Irritante')
        db.t_sustancias.insert(f_nombre='4-metilpentan-2-ona (Metilisobutilcetona)', f_cas='108-10-1', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Acetato de Etilo', f_cas='141-78-6', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Irritante')
        db.t_sustancias.insert(f_nombre='Acetona', f_cas='67-64-1', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Ácido Antranílico', f_cas='118-92-3', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Comburente')
        db.t_sustancias.insert(f_nombre='Ácido Clorhídrico', f_cas='7647-01-0', f_pureza='37', f_estado='2', f_control='1', f_peligrosidad='Corrosivo')
        db.t_sustancias.insert(f_nombre='Ácido Nítrico', f_cas='7697-37-2', f_pureza='5', f_estado='2', f_control='2', f_peligrosidad='Irritante')
        db.t_sustancias.insert(f_nombre='Ácido Pícrico (trinitrofenol)', f_cas='88-89-1', f_pureza='3', f_estado='1', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Ácido Sulfúrico', f_cas='7664-93-9', f_pureza='97', f_estado='2', f_control='3', f_peligrosidad='Irritante')
        db.t_sustancias.insert(f_nombre='Amoníaco Anhídrico', f_cas='7664-41-7', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Amoníaco en disolución acuosa', f_cas='001336-21-6', f_pureza='25', f_estado='2', f_control='1', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Anhídrico acético', f_cas='108-24-7', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Nocivo')
        db.t_sustancias.insert(f_nombre='Benceno', f_cas='71-43-2', f_pureza='99', f_estado='2', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Butanona (metilcetona)', f_cas='78-93-3', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Carbonato de Sodio', f_cas='497-19-8', f_pureza='99', f_estado='1', f_control='1', f_peligrosidad='Irritante')
        db.t_sustancias.insert(f_nombre='Clorato de Potasio', f_cas='3811-04-9', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Clorato de Sodio', f_cas='7775-09-9', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Cloroformo', f_cas='67-66-3', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Diclorometano', f_cas='75-09-2', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Inflamable')
        db.t_sustancias.insert(f_nombre='Dinitrofenol', f_cas='51-28-5', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Etanol', f_cas='64-17-5', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Irritante')
        db.t_sustancias.insert(f_nombre='Eter Etílico', f_cas='60-29-7', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Nocivo')
        db.t_sustancias.insert(f_nombre='Fósforo blanco', f_cas='7723-14-0', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Nocivo')
        db.t_sustancias.insert(f_nombre='Heptano', f_cas='142-82-5', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Irritante')
        db.t_sustancias.insert(f_nombre='Hipoclorito de calcio', f_cas='7778-54-3', f_pureza='68', f_estado='1', f_control='2', f_peligrosidad='Irritante')
        db.t_sustancias.insert(f_nombre='Hipoclorito de Sodio', f_cas='7681-52-9', f_pureza='', f_estado='2', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Metanol', f_cas='67-56-1', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Irritante')
        db.t_sustancias.insert(f_nombre='Nitrato de Bismuto', f_cas='7697-37-2', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Nitrato de Plata', f_cas='7761-88-8', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Nitrato de Plomo', f_cas='10099-74-8', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Nitrato de Potasio', f_cas='7757-79-1', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Nitrato de Sodio', f_cas='7631-99-4', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Nitrito de Sodio', f_cas='7632-00-0', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Nitrobenceno', f_cas='98-95-3', f_pureza='99', f_estado='2', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Perclorato de Potasio', f_cas='7778-74-7', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Perclorato de Sodio', f_cas='7601-89-0', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Nocivo')
        db.t_sustancias.insert(f_nombre='Permanganato de Potasio', f_cas='7722-64-7', f_pureza='99', f_estado='1', f_control='3', f_peligrosidad='Corrosivo')
        db.t_sustancias.insert(f_nombre='Sesquicarbonato de Sodio', f_cas='6106-20-3', f_pureza='99', f_estado='1', f_control='1', f_peligrosidad='Irritante')
        db.t_sustancias.insert(f_nombre='Sulfato de Amonio', f_cas='7783-20-2', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Irritante')
        db.t_sustancias.insert(f_nombre='Sulfuro de Potasio', f_cas='1312-73-8', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Corrosivo')
        db.t_sustancias.insert(f_nombre='Tetrahidrofurano', f_cas='109-99-9', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Irritante')
        db.t_sustancias.insert(f_nombre='Tolueno', f_cas='108-88-3', f_pureza='99', f_estado='2', f_control='1', f_peligrosidad='Tóxico')
        db.t_sustancias.insert(f_nombre='Trinitrotolueno (TNT)', f_cas='118-96-7', f_pureza='99', f_estado='1', f_control='2', f_peligrosidad='Nocivo')
        db.t_sustancias.insert(f_nombre='Urea', f_cas='57-13-6 ', f_pureza='', f_estado='1', f_control='2', f_peligrosidad='Comburente')
        #####Deberian ser RL8 pero este regimen aun no esta implementado
        db.t_sustancias.insert(f_nombre='Fósforos rojos o amorfos', f_cas='7723-14-0', f_pureza='99', f_estado='1', f_control='4', f_peligrosidad='Inflamable | Nocivo')


    # llenamos si solo está presente el superuser
    # solo jefes de lab y de seccion
    if db(db.auth_user).count() <= 1:

        db.auth_user.insert(first_name="No", last_name="Asignado", email='no_asig@usb.ve', cargo=db(db.auth_group.role == "Usuario Normal").select(db.auth_group.id).first(), autorizado=True)
        #labs
        id_jefe = db(db.auth_group.role == "Jefe de Laboratorio").select(db.auth_group.id).first()

        db.auth_user.insert(email='cherrera@usb.ve', cargo=id_jefe, autorizado=True)
        db.auth_user.insert(email='chickani@usb.ve', cargo=id_jefe, autorizado=True)
        db.auth_user.insert(email='eprato@usb.ve', cargo=id_jefe, autorizado=True)
        db.auth_user.insert(email='jrodrig@usb.ve', cargo=id_jefe, autorizado=True)
        db.auth_user.insert(email='jwalter@usb.ve', cargo=id_jefe, autorizado=True)
        db.auth_user.insert(email='rcastell@usb.ve', cargo=id_jefe, autorizado=True)
        db.auth_user.insert(email='wsequera@usb.ve', cargo=id_jefe, autorizado=True)

        #sec
        id_jefe_s = db(db.auth_group.role == "Jefe de Sección").select(db.auth_group.id).first()

        db.auth_user.insert(email='severeynerika@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='cizarra@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='abello@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='hbarros@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='antoniovidal@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='grodriguez@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='ccorrale@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='jmelendez@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='jwrengifo@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='mggomez@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='sdiaz@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='cherrera@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='deisyperdomo@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='eklein@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='eliergalarraga@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='elucci@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='epenott@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='erikapedraza@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='grincon@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='lubesv@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='mariaesthermoline@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='msabino@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='nelsonaraujo@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='psuarez@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='rmichell@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='ronaldvargas@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='vlandaeta@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='amendoza@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='amolina@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='mnino@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='nleon@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='racosta@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='sovilla@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='xhung@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='violetta@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='aamerio@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='adenisraga@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='chechelev@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='dleal@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='elsacardenas@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='hrssca@hotmail.com', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='jgutierr@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='kgomez@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='oescobar@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='eguerre@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='rescal@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='clladera@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='jgruiz@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='lguarino@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='neilmartinez@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='hrojas@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='yudith@ldc.usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='avargas@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='mrivas@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='nmagdaleno@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='adiserio@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='mgoncalves@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='mscembo@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='jacob@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='isabel.llatas@gmail.com', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='lusitano@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='martinez@ldc.usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='emendez@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='gpalma@ldc.usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='aizarra@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='figueira@ldc.usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='eduardo@ldc.usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='camayora@usb.ve', cargo=id_jefe_s, autorizado=True)
        db.auth_user.insert(email='wgonzal@usb.ve', cargo=2, autorizado=True)
        db.auth_user.insert(email='yortega@usb.ve', cargo=4, autorizado=True)
        db.auth_user.insert(email='mmacias@usb.ve', cargo=3, autorizado=True)

    if db(db.t_users_autorizados).isempty():
        id_tec = db(db.auth_group.role == "Técnico").select(db.auth_group.id).first()

        db.t_users_autorizados.insert(f_email='adegouveia@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='aguillon@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='hcmarquez@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='iacosta@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='jesu.alberto.pinto.alayon@gmail',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='luisalas@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='mdacosta@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='npulido@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='ragarcia@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='rcorreia@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='vmonagas@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='07-41753@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='13-89428@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='adesousa@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='dalizo@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='dannyvalera@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='ezambrano@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='freddyrojas@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='ggedler@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='imelendez@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='luhidalgo@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='nciguela@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='noeliarodriguez@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='oscaruiz@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='pmoncada@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='sdeleon@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='vfigueroa@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='ymunoz@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='gvillega@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='jesusrojas@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='ralejos@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='marchena@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='rlugo@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='zsierra@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='aalcalde@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='abenitez@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='alvarezf@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='cvitanza@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='dgraciano@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='fmflores@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='grodrig@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='guillent@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='hgalezo@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='ialvarado@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='jmoreno@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='jyannuzzo@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='kaponte@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='magonzal@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='psoto@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='seijascarla@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='fabiolarojas@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='gjean@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='mbolivar@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='mbolivar@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='scovino@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='tomasgrt@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='wsanchez@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='bchirinos@usb.ve',f_group=id_tec)
        db.t_users_autorizados.insert(f_email='lualvare@usb.ve',f_group=id_tec)

    ###Laboratorios
    if db(db.t_laboratorio).isempty():
        db.t_laboratorio.insert(f_nombre='Laboratorio A',f_jefe=db(db.auth_user.email == 'jrodrig@usb.ve').select(db.auth_user.id).first())
        db.t_laboratorio.insert(f_nombre='Laboratorio B',f_jefe=db(db.auth_user.email == 'cherrera@usb.ve').select(db.auth_user.id).first())
        db.t_laboratorio.insert(f_nombre='Laboratorio C',f_jefe=db(db.auth_user.email == 'jwalter@usb.ve').select(db.auth_user.id).first())
        db.t_laboratorio.insert(f_nombre='Laboratorio D',f_jefe=db(db.auth_user.email == 'rcastell@usb.ve').select(db.auth_user.id).first())
        db.t_laboratorio.insert(f_nombre='Laboratorio E',f_jefe=db(db.auth_user.email == 'eprato@usb.ve').select(db.auth_user.id).first())
        db.t_laboratorio.insert(f_nombre='Laboratorio F',f_jefe=db(db.auth_user.email == 'wsequera@usb.ve').select(db.auth_user.id).first())
        db.t_laboratorio.insert(f_nombre='Laboratorio G',f_jefe=db(db.auth_user.email == 'chickani@usb.ve').select(db.auth_user.id).first())

    ##Secciones
    if db(db.t_seccion).isempty():
        id_a = db(db.t_laboratorio.f_nombre == 'Laboratorio A').select(db.t_laboratorio.id).first()
        db.t_seccion.insert(f_seccion='Alta Tensión',f_laboratorio=id_a, f_jefe=db(db.auth_user.email == 'jrodrig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Conversión de Energía Eléctrica',f_laboratorio=id_a,f_jefe=db(db.auth_user.email == 'jwrengifo@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Conversión de Energía Mecánica',f_laboratorio=id_a,f_jefe=db(db.auth_user.email == 'antoniovidal@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Desarrollo de Modelos y Prototipos',f_laboratorio=id_a,f_jefe=db(db.auth_user.email == 'jrodrig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Dinámica de Máquinas',f_laboratorio=id_a,f_jefe=db(db.auth_user.email == 'sdiaz@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Fenómenos de Transporte',f_laboratorio=id_a,f_jefe=db(db.auth_user.email == 'jmelendez@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Mecánica Computacional',f_laboratorio=id_a,f_jefe=db(db.auth_user.email == 'grodriguez@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Mecánica de Fluidos',f_laboratorio=id_a,f_jefe=db(db.auth_user.email == 'ccorrale@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Operaciones Unitarias',f_laboratorio=id_a,f_jefe=db(db.auth_user.email == 'mggomez@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Sistemas de Potencia',f_laboratorio=id_a,f_jefe=db(db.auth_user.email == 'jrodrig@usb.ve').select(db.auth_user.id).first())

        id_b = db(db.t_laboratorio.f_nombre == 'Laboratorio B').select(db.t_laboratorio.id).first()
        db.t_seccion.insert(f_seccion='Alimentos',f_laboratorio=id_b,f_jefe=db(db.auth_user.email == 'elucci@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Bioterio',f_laboratorio=id_b,f_jefe=db(db.auth_user.email == 'deisyperdomo@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Biología Celular',f_laboratorio=id_b,f_jefe=db(db.auth_user.email == 'nelsonaraujo@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Biología de Organismos',f_laboratorio= id_b,f_jefe=db(db.auth_user.email == 'psuarez@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Biología Marina',f_laboratorio=id_b,f_jefe=db(db.auth_user.email == 'eklein@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Ecología',f_laboratorio=id_b,f_jefe=db(db.auth_user.email == 'erikapedraza@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Físico Química',f_laboratorio=id_b,f_jefe=db(db.auth_user.email == 'ronaldvargas@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Nutrición',f_laboratorio=id_b,f_jefe=db(db.auth_user.email == 'mariaesthermoline@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Polímeros',f_laboratorio=id_b,f_jefe=db(db.auth_user.email == 'epenott@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Procesos Químicos',f_laboratorio=id_b,f_jefe=db(db.auth_user.email == 'grincon@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Química Analítica',f_laboratorio=id_b,f_jefe=db(db.auth_user.email == 'cherrera@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Química General',f_laboratorio=id_b,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Química Inorgánica',f_laboratorio=id_b,f_jefe=db(db.auth_user.email == 'lubesv@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Química Orgánica',f_laboratorio=id_b,f_jefe=db(db.auth_user.email == 'eliergalarraga@usb.ve').select(db.auth_user.id).first())

        id_c = db(db.t_laboratorio.f_nombre == 'Laboratorio C').select(db.t_laboratorio.id).first()
        db.t_seccion.insert(f_seccion='Redes, Electrónica Analógica y Digital',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'jwalter@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Procesamiento de Señales y Sistemas',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Comunicaciones',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'jwalter@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Instrumentación y Control de Procesos y Sistemas',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Centro de Automatización Industrial',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Electrónica de Potencia',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'jwalter@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Sistemas Digitales',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Telecomunicaciones',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Mecatrónica',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'jwalter@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Control Automático',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Acústica y Comunicaciones',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Estado Sólido',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Biomecánica',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Sistemas Biomédicos',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Procesamiento de Señales y Sistemas',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'jwalter@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Grupo de Redes Electrónicas y Telemática Aplicada (GRETA)',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Grupo de Procesamiento de Señales (GPS)',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Grupo de Telecomunicaciones (GTEL)',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Grupo de Centro y Automatización Industrial (CAI)',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Grupo de Sistemas Industriales de Electrónica de Potencia (SIEP)',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Grupo de Laboratorio de Investigación en Sistemas de Información (LISI)',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Grupo de Mecatrónica',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Grupo de Biomecánica',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Laboratorio de Control Automático (LCA).',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Grupo de Energía Alternativa (GEA)',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Grupo de Laboratorio de Electrónica de Estados Sólidos (LEES)',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Grupo de Biomecánica, Rehabilitación y Procesamiento de Señales (GBRPS)',f_laboratorio=id_c,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())

        id_d = db(db.t_laboratorio.f_nombre == 'Laboratorio D').select(db.t_laboratorio.id).first()
        db.t_seccion.insert(f_seccion='Biofísica',f_laboratorio=id_d,f_jefe=db(db.auth_user.email == 'severeynerika@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Espectroscopía Laser ',f_laboratorio=id_d,f_jefe=db(db.auth_user.email == 'rcastell@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Física de Estado Sólido',f_laboratorio=id_d,f_jefe=db(db.auth_user.email == 'abello@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Física Nuclear',f_laboratorio=id_d,f_jefe=db(db.auth_user.email == 'hbarros@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Geofísica',f_laboratorio=id_d,f_jefe=db(db.auth_user.email == 'cizarra@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Laboratorio de Demostraciones',f_laboratorio=id_d,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Laboratorios Avanzados y de Post-grado',f_laboratorio=id_d,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Laboratorios Básicos',f_laboratorio=id_d,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Laboratorios Intermedios',f_laboratorio=id_d,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Simulaciones de la Materia Condensada',f_laboratorio=id_d,f_jefe=db(db.auth_user.email == 'eguerre@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Óptica',f_laboratorio=id_d,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Óptica e Interferometría',f_laboratorio=id_d,f_jefe=db(db.auth_user.email == 'rescal@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Óptica Moderna y Aplicada',f_laboratorio=id_d,f_jefe=db(db.auth_user.email == 'clladera@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Plasma Contínua y Pulsada',f_laboratorio=id_d,f_jefe=db(db.auth_user.email == 'jgruiz@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Psicofisiología y Conducta Humana ',f_laboratorio=id_d,f_jefe=db(db.auth_user.email == 'lguarino@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Sólidos I',f_laboratorio=id_d,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())

        id_e = db(db.t_laboratorio.f_nombre == 'Laboratorio E').select(db.t_laboratorio.id).first()
        db.t_seccion.insert(f_seccion='Cerámica y Suelos',f_laboratorio=id_e,f_jefe=db(db.auth_user.email == 'neilmartinez@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Coordinación de Actividades Técnicas',f_laboratorio=id_e,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Coordinación de Aseguramiento de la Calidad ',f_laboratorio=id_e,f_jefe=db(db.auth_user.email == 'hrojas@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Coordinación de Mantenimiento y Sistemas',f_laboratorio=id_e,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Corrosión',f_laboratorio=id_e,f_jefe=db(db.auth_user.email == 'amendoza@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Materiales',f_laboratorio=id_e,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Metalurgia Química',f_laboratorio=id_e,f_jefe=db(db.auth_user.email == 'amolina@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Metrología Dimensional',f_laboratorio=id_e,f_jefe=db(db.auth_user.email == 'racosta@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Microscopía Electrónica',f_laboratorio=id_e,f_jefe=db(db.auth_user.email == 'amolina@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Polímeros',f_laboratorio=id_e,f_jefe=db(db.auth_user.email == 'nleon@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Procesos Metalmecánicos',f_laboratorio=id_e,f_jefe=db(db.auth_user.email == 'racosta@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Procesos Metalúrgicos',f_laboratorio=id_e,f_jefe=db(db.auth_user.email == 'mnino@usb.ve').select(db.auth_user.id).first())

        id_f = db(db.t_laboratorio.f_nombre == 'Laboratorio F').select(db.t_laboratorio.id).first()
        db.t_seccion.insert(f_seccion='Aulas Computarizadas',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'yudith@ldc.usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Computacional de Ciencia Política',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'avargas@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Informática Educativa',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'mrivas@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Lengua - José Santos Urriola',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'nmagdaleno@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Computación',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'adiserio@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Redes y Bases de Datos',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'mgoncalves@ldc.usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Diseño Asistido por Computadora',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'mscembo@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Matemáticas y Estadísticas Computacionales',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'jacob@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Centro de Estadística y Software Matemático',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'isabel.llatas@gmail.com').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Bases de Datos',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'mgoncalves@ldc.usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Computación Gráfica y Multimedia',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Geomática Urbana',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'lusitano@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Inteligencia Artificial',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'martinez@ldc.usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Investigación en Sistemas de Información',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'emendez@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Lenguajes y Algoritmos',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'gpalma@ldc.usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Digital de Música',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'aizarra@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Sistemas Paralelos y Distribuidos',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'figueira@ldc.usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Computación de Alto Rendimiento',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'eduardo@ldc.usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Estudios Tecnológicos',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'yudith@ldc.usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Idiomas Asistido por Computadoras ',f_laboratorio=id_f,f_jefe=db(db.auth_user.email == 'camayora@usb.ve').select(db.auth_user.id).first())

        id_g = db(db.t_laboratorio.f_nombre == 'Laboratorio G').select(db.t_laboratorio.id).first()
        db.t_seccion.insert(f_seccion='Conversión de Energía Electrica (Litoral)',f_laboratorio=id_g,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Conversión de Energía Mecánica (Litoral)',f_laboratorio=id_g,f_jefe=db(db.auth_user.email == 'elsacardenas@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Aeronaves (Litoral)',f_laboratorio=id_g,f_jefe=db(db.auth_user.email == 'aamerio@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Procesos Mecánicos de Fabricación y Materiales (Litoral)',f_laboratorio=id_g,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Física (Litoral)',f_laboratorio=id_g,f_jefe=db(db.auth_user.email == 'chechelev@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Fundamentos de Circuitos Eléctricos (Litoral)',f_laboratorio=id_g,f_jefe=db(db.auth_user.email == 'hrssca@hotmail.com').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Digitales (Litoral)',f_laboratorio=id_g,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Intrumentación y Control (Litoral)',f_laboratorio=id_g,f_jefe=db(db.auth_user.email == 'dleal@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Biomédica (Litoral)',f_laboratorio=id_g,f_jefe=db(db.auth_user.email == 'kgomez@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Tecnologías de la Información (Litoral)',f_laboratorio=id_g,f_jefe=db(db.auth_user.email == 'chikhani@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Telemática (Litoral)',f_laboratorio=id_g,f_jefe=db(db.auth_user.email == 'jgutierr@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Comunicaciones (Litoral)',f_laboratorio=id_g,f_jefe=db(db.auth_user.email == 'oescobar@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Idiomas (Litoral)',f_laboratorio=id_g,f_jefe=db(db.auth_user.email == 'adenisraga@usb.ve').select(db.auth_user.id).first())
        db.t_seccion.insert(f_seccion='Alimentos y Bebidas (Litoral)',f_laboratorio=id_g,f_jefe=db(db.auth_user.email == 'no_asig@usb.ve').select(db.auth_user.id).first())

    if db(db.t_espaciofisico).isempty():
        db.t_espaciofisico.insert(f_direccion="ALT-001A",f_espacio="Sala de equipos de interconexion a internet",f_seccion=(db(db.t_seccion.f_seccion == "Alta Tensión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ALT-003",f_espacio="Sala de ensayos hasta 200 KV 60 Hz",f_seccion=(db(db.t_seccion.f_seccion == "Alta Tensión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ALT-004",f_espacio="Sala para el kit de alta tension",f_seccion=(db(db.t_seccion.f_seccion == "Alta Tensión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ALT-004A",f_espacio="Sala de instrumentos",f_seccion=(db(db.t_seccion.f_seccion == "Alta Tensión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ALT-005",f_espacio="Sala de tesistas",f_seccion=(db(db.t_seccion.f_seccion == "Alta Tensión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ALT-006",f_espacio="Sala principal de ensayos",f_seccion=(db(db.t_seccion.f_seccion == "Alta Tensión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ALT-007",f_espacio="Sala de control de equipos de AT",f_seccion=(db(db.t_seccion.f_seccion == "Alta Tensión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ALT-008",f_espacio="Oficina del Técnico",f_seccion=(db(db.t_seccion.f_seccion == "Alta Tensión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ALT-009",f_espacio="Taller de uso general",f_seccion=(db(db.t_seccion.f_seccion == "Alta Tensión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ALT-009A",f_espacio="Sala de pararrayos",f_seccion=(db(db.t_seccion.f_seccion == "Alta Tensión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ALT-103",f_espacio="Gradas",f_seccion=(db(db.t_seccion.f_seccion == "Alta Tensión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ALT-S01",f_espacio=" Subestación",f_seccion=(db(db.t_seccion.f_seccion == "Alta Tensión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="CB1-Piso 1",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Informática Educativa").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="CB1-228",f_espacio="Laboratorio de Evaluación Nutricional",f_seccion=(db(db.t_seccion.f_seccion == "Nutrición").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="CB1-231",f_espacio="Laboratorio Docente Polimeros",f_seccion=(db(db.t_seccion.f_seccion == "Polímeros").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="CB1-232",f_espacio="Laboratorio Investigacion Polimeros",f_seccion=(db(db.t_seccion.f_seccion == "Polímeros").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="CB1-315",f_espacio="Lab. Biologia Marina",f_seccion=(db(db.t_seccion.f_seccion == "Biología Marina").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="CB1-316",f_espacio="Lab. Biologia Marina",f_seccion=(db(db.t_seccion.f_seccion == "Biología Marina").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="CB1-317",f_espacio="Lab. Biologia Marina",f_seccion=(db(db.t_seccion.f_seccion == "Biología Marina").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="CB1-318",f_espacio="Laboratorio Nutrición",f_seccion=(db(db.t_seccion.f_seccion == "Nutrición").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="CB1-319",f_espacio="Laboratorio Nutrición",f_seccion=(db(db.t_seccion.f_seccion == "Nutrición").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="CB1-320",f_espacio="Laboratorio Nutricional",f_seccion=(db(db.t_seccion.f_seccion == "Nutrición").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="CB1-321",f_espacio="Laboratorio Nutricional",f_seccion=(db(db.t_seccion.f_seccion == "Nutrición").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="CB1-322",f_espacio="    ",f_seccion=(db(db.t_seccion.f_seccion == "Nutrición").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="EGE-215",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Idiomas Asistido por Computadoras ").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-119",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Investigación en Sistemas de Información").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FE1-121",f_espacio="Laboratorio de Biofísica",f_seccion=(db(db.t_seccion.f_seccion == "Biofísica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FE2-Piso 1",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Lengua - José Santos Urriola").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FE2-Piso 1",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Computación de Alto Rendimiento").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FE1-124",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Computacional de Ciencia Política").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FE2-001",f_espacio="Microscopía, conductividad",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio de Sólidos I").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FE2-004",f_espacio="Chiller de enfriamiento-Mantenimiento",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio de Sólidos I").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FE2-005",f_espacio="'Mediciones de TSDC, muestras",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio de Sólidos I").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FE2-006",f_espacio="'Laboratorio de Difraccion Rayos X, Mediciones de corrientes TE",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio de Sólidos I").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FE2-007A",f_espacio="Espectrometría Dieléctrica",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio de Sólidos I").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FE2-010",f_espacio="Sala de computación-Seminarios",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio de Sólidos I").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-001A",f_espacio="Oficina ",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-001B",f_espacio="Jefatura de la Sección ",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-002",f_espacio="Sala de Reuniones ",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-005",f_espacio="Oficina",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-006",f_espacio="Oficina",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-007",f_espacio="Oficina",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-008",f_espacio="Oficina",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-009",f_espacio="Sala de Herramientas ",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-010",f_espacio="Laboratorio / Grupo SAE / Taller / Grupo SAE-Aviación",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-012",f_espacio="Oficina de Secretaria ",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-013",f_espacio="Depósito de vidrio",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-014",f_espacio="Laboratorio de Óptica",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-015",f_espacio="Laboratorio de Reología",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-016",f_espacio="Taller",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-017",f_espacio="Laboratorio de Quimica",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-018",f_espacio="Deposito de Ferrertería",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-019",f_espacio="Baño",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-020",f_espacio="Baño",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-021",f_espacio="Sala de Instrumental",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-022",f_espacio="Oficina del técnico",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-023",f_espacio="Área del Laboratorio (planta baja)",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-023A",f_espacio="Depósito de reactivo",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-101",f_espacio="Sala de Computación",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-101A",f_espacio="Oficina de Calidad",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-102",f_espacio="Prácticas de laboratorio ",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-102",f_espacio="Sala de tesistas",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-102A",f_espacio="Oficina",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-102B",f_espacio="Oficina de Tesistas III",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-102C",f_espacio="Oficina ",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-102D",f_espacio="Oficina de Dibujo ",f_seccion=(db(db.t_seccion.f_seccion == "Mecánica de Fluidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-104",f_espacio="Sala de computadoras",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-105",f_espacio="Cocina",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-106",f_espacio="OFICINA",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-107",f_espacio="OFICINA",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-108",f_espacio="Cubículo de investigación ",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-109",f_espacio="Cubículo de investigación ",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-110",f_espacio="Cubículo de investigación ",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-111",f_espacio="Cubículo de investigación ",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-112",f_espacio="Baño",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-113",f_espacio="Baño",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-114",f_espacio="OFICINA",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-115",f_espacio="OFICINA",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-116",f_espacio="OFICINA",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-117",f_espacio="OFICINA",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-118",f_espacio="OFICINA",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-119",f_espacio="OFICINA",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="FOP-120",f_espacio="Sala de conferencias/Aula",f_seccion=(db(db.t_seccion.f_seccion == "Operaciones Unitarias").select(db.t_seccion.id).first()))
        #db.t_espaciofisico.insert(f_direccion="LPD-007",f_espacio="Prácticas de Taller Básico  / Mantenimiento Mecánico",Conversión de Energía Mecánica y Fluidos,f_seccion=(db(db.t_seccion.f_seccion == "N/D").select(db.t_seccion.id).first()))
        #db.t_espaciofisico.insert(f_direccion="LPD-009",f_espacio="Prácticas de Fluidos I y II",Conversión de Energía Mecánica y Fluidos,f_seccion=(db(db.t_seccion.f_seccion == "N/D").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MEU-118",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Geomática Urbana").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MEU-212",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Diseño Asistido por Computadora").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MTE-002",f_espacio="Laboratorio de Extrusión",f_seccion=(db(db.t_seccion.f_seccion == "Polímeros").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MTE-003",f_espacio="Laboratorio de Extrusión",f_seccion=(db(db.t_seccion.f_seccion == "Polímeros").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MTE-014",f_espacio="Laboratorio de Mezclado",f_seccion=(db(db.t_seccion.f_seccion == "Polímeros").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MTE-103",f_espacio="Sección de Polímeros",f_seccion=(db(db.t_seccion.f_seccion == "Polímeros").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MTE-105",f_espacio="Sección de Polímeros",f_seccion=(db(db.t_seccion.f_seccion == "Polímeros").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MTE-113",f_espacio="Laboratorio de Propiedades Físicas",f_seccion=(db(db.t_seccion.f_seccion == "Polímeros").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MTE-114",f_espacio="Laboratorio de Reología Polímeros",f_seccion=(db(db.t_seccion.f_seccion == "Polímeros").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MTE-115",f_espacio="Laboratorio de Pinturas",f_seccion=(db(db.t_seccion.f_seccion == "Polímeros").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-209B",f_espacio="Maestría en Música/Estudios Generales",f_seccion=(db(db.t_seccion.f_seccion == "Digital de Música").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-006",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Estudios Tecnológicos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-013",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Aulas Computarizadas").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-015",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Computación").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-016",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Aulas Computarizadas").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-019",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Aulas Computarizadas").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-104",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Sistemas Paralelos y Distribuidos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-105",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Bases de Datos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-106",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Bases de Datos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-108",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Centro de Estadística y Software Matemático").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-109",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Centro de Estadística y Software Matemático").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-110",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Computación Gráfica y Multimedia").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-120",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Matemáticas y Estadísticas Computacionales").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-209",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Lenguajes y Algoritmos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-209B",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Digital de Música").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-221",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Computación").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-222",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Computación").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-223",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Computación").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-224",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Computación").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-225",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Computación").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="MYS-PB",f_espacio="Laboratorio Docente e Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Inteligencia Artificial").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-340",f_espacio="Lab. Instrumental",f_seccion=(db(db.t_seccion.f_seccion == "Química Analítica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-002",f_espacio="Laboratorio Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Físico Química").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-003",f_espacio="Sala de Tesistas",f_seccion=(db(db.t_seccion.f_seccion == "Físico Química").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-004",f_espacio="Labratorio de Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Físico Química").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-005",f_espacio="Oficina ",f_seccion=(db(db.t_seccion.f_seccion == "Físico Química").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-006",f_espacio="Sala de Conferencia",f_seccion=(db(db.t_seccion.f_seccion == "Físico Química").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-007",f_espacio="Laboratorio de Docencia",f_seccion=(db(db.t_seccion.f_seccion == "Físico Química").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-012",f_espacio="Almacén de Química",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio B").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-113",f_espacio="Laboratorio de Alimento",f_seccion=(db(db.t_seccion.f_seccion == "Alimentos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-014",f_espacio="Taller de Mantenimiento",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio B").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-015",f_espacio="Laboratorio Resonancia Magnética RMN",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio B").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-018",f_espacio="Laboratorio Electroquímica",f_seccion=(db(db.t_seccion.f_seccion == "Físico Química").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-019",f_espacio="Oficina del Laboratorio B",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio B").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-020",f_espacio="Sala de preparación de muestras ",f_seccion=(db(db.t_seccion.f_seccion == "Química General").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-020",f_espacio="Sala de preparación de muestras ",f_seccion=(db(db.t_seccion.f_seccion == "Química General").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-021",f_espacio="Laboratorio Química General",f_seccion=(db(db.t_seccion.f_seccion == "Química General").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-022",f_espacio="Laboratorio Química General",f_seccion=(db(db.t_seccion.f_seccion == "Química General").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-023",f_espacio="Taller Soplado de Vidrio",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio B").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-024",f_espacio="Taller Soplado de Vidrio",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio B").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-025A",f_espacio="Oficina Química General",f_seccion=(db(db.t_seccion.f_seccion == "Química General").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-104",f_espacio="Laboratorio de Análitica",f_seccion=(db(db.t_seccion.f_seccion == "Química Analítica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-108",f_espacio="Laboratorio de Espectroscopia",f_seccion=(db(db.t_seccion.f_seccion == "Química Analítica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-113",f_espacio="Lab. Desarrollo de Nuevos Productos",f_seccion=(db(db.t_seccion.f_seccion == "Alimentos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-122",f_espacio="Sala de Profesores",f_seccion=(db(db.t_seccion.f_seccion == "Alimentos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-124",f_espacio="Oficina de Técnicos",f_seccion=(db(db.t_seccion.f_seccion == "Alimentos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-127",f_espacio="Lab. Análisis de Alimentos",f_seccion=(db(db.t_seccion.f_seccion == "Alimentos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-129",f_espacio="Lab. Microbiología",f_seccion=(db(db.t_seccion.f_seccion == "Alimentos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-131",f_espacio="Lab. Planta Piloto",f_seccion=(db(db.t_seccion.f_seccion == "Alimentos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-132",f_espacio="Oficina Prof.",f_seccion=(db(db.t_seccion.f_seccion == "Alimentos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-134",f_espacio="Lab. Análisis Sensorial",f_seccion=(db(db.t_seccion.f_seccion == "Alimentos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-135",f_espacio="Cocina Experimental",f_seccion=(db(db.t_seccion.f_seccion == "Alimentos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-225",f_espacio="Lab. Sintesis y Determinaciones",f_seccion=(db(db.t_seccion.f_seccion == "Química Orgánica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-226",f_espacio="Lab. de Inorgánica",f_seccion=(db(db.t_seccion.f_seccion == "Química Inorgánica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-227",f_espacio="Lab. de Orgánica para Ingenieros",f_seccion=(db(db.t_seccion.f_seccion == "Química Orgánica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-228",f_espacio="Lab. de Orgánica",f_seccion=(db(db.t_seccion.f_seccion == "Química Orgánica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-229",f_espacio="Sala de Técnicos",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio B").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-325",f_espacio="Sala de Computadoras",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio B").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-342",f_espacio="Lab. Fitoquímica",f_seccion=(db(db.t_seccion.f_seccion == "Química Orgánica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-343",f_espacio="Lab. de Alimentos",f_seccion=(db(db.t_seccion.f_seccion == "Química Analítica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-344",f_espacio="Lab. de Alimentos",f_seccion=(db(db.t_seccion.f_seccion == "Química Analítica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-345",f_espacio="Lab. de Alimentos",f_seccion=(db(db.t_seccion.f_seccion == "Química Analítica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-346",f_espacio="Lab. de Alimentos",f_seccion=(db(db.t_seccion.f_seccion == "Química Analítica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-347",f_espacio="Lab. Catalisis",f_seccion=(db(db.t_seccion.f_seccion == "Química Inorgánica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-348",f_espacio="Lab de Investigación",f_seccion=(db(db.t_seccion.f_seccion == "Química Inorgánica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-349",f_espacio="Lab. Investigacion",f_seccion=(db(db.t_seccion.f_seccion == "Química Inorgánica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="QYP-351",f_espacio="Lab. Investigacion",f_seccion=(db(db.t_seccion.f_seccion == "Química Inorgánica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-001",f_espacio="Laboratorio de Fundición",f_seccion=(db(db.t_seccion.f_seccion == "Procesos Metalúrgicos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-002",f_espacio="Laboratorio de Tratamientos Térmicos",f_seccion=(db(db.t_seccion.f_seccion == "Procesos Metalúrgicos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-003",f_espacio="Laboratorio de Arenas",f_seccion=(db(db.t_seccion.f_seccion == "Procesos Metalúrgicos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-006",f_espacio="Comedor",f_seccion=(db(db.t_seccion.f_seccion == "Procesos Metalúrgicos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-012B",f_espacio="Almacén ",f_seccion=(db(db.t_seccion.f_seccion == "Procesos Metalúrgicos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-103",f_espacio="Laboratorio de Corrosión",f_seccion=(db(db.t_seccion.f_seccion == "Corrosión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-104",f_espacio="Aula",f_seccion=(db(db.t_seccion.f_seccion == "Corrosión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-105",f_espacio="Sala de muestras y balanzas",f_seccion=(db(db.t_seccion.f_seccion == "Corrosión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-106",f_espacio="Oficinas",f_seccion=(db(db.t_seccion.f_seccion == "Corrosión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-107",f_espacio="Comedor",f_seccion=(db(db.t_seccion.f_seccion == "Corrosión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-108",f_espacio="Sala de Termobalanza",f_seccion=(db(db.t_seccion.f_seccion == "Corrosión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-112",f_espacio="Jefatura de Sección Procesos Metalúgicos",f_seccion=(db(db.t_seccion.f_seccion == "Procesos Metalúrgicos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-113",f_espacio="Jefatura sección de Corrosión",f_seccion=(db(db.t_seccion.f_seccion == "Corrosión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-114",f_espacio="Oficina ",f_seccion=(db(db.t_seccion.f_seccion == "Procesos Metalúrgicos").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-115",f_espacio="Sala de tesistas",f_seccion=(db(db.t_seccion.f_seccion == "Corrosión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-116",f_espacio="Oficina Técnico",f_seccion=(db(db.t_seccion.f_seccion == "Corrosión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="TRT-117",f_espacio="Laboratorio preparación metalográfica",f_seccion=(db(db.t_seccion.f_seccion == "Corrosión").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-005",f_espacio="Taller (GEA)", f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Energía Alternativa (GEA)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-008",f_espacio="Sala de Tesistas y Proyecto (LCA)",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio de Control Automático (LCA)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-008A",f_espacio="Laboratorio de Profesores",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio de Control Automático (LCA)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-009",f_espacio="Docencia",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio de Control Avanzado").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-010",f_espacio="Docencia",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio de Control con PLC").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-012",f_espacio="Docencia",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio de Control Básico").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-013",f_espacio="Oficina  de Profesores (CAI)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Control y Automatización Industrial (CAI)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-018",f_espacio="Laboratorio de Profesores (SIEP)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Sistemas Industriales de Electrónica de Potencia (SIEP)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-019",f_espacio="Laboratorio de Profesores y Tesistas (SIEP)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Sistemas Industriales de Electrónica de Potencia (SIEP)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-020",f_espacio="Laboratorio de Profesores (IEES)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Laboratorio de Electrónica de Estados Sólidos (LEES)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-021",f_espacio="Laboratorio de Profesores (IEES)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Laboratorio de Electrónica de Estados Sólidos (LEES)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-022",f_espacio="Laboratorio de Profesores (IEES)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Laboratorio de Electrónica de Estados Sólidos (LEES)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-023",f_espacio="Laboratorio de Tesistas (IEES)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Laboratorio de Electrónica de Estados Sólidos (LEES)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-101",f_espacio="Docencia",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio de Electrónica de Potencia").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-105",f_espacio="Docencia",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio Universal").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-107",f_espacio="Docencia ",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio Universal").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-108",f_espacio="Docencia ",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio Universal").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-109",f_espacio="Docencia ",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio Universal").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-110",f_espacio="Docencia ",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio Universal").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-111",f_espacio="Laboratorio de Profesores (GBBA)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Bioingeniería y Biofísica Aplicada (GBBA)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-112",f_espacio="Laboratorio de Profesores y Tesistes (GRETA)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Redes Electrónicas y Telemática Aplcada (GRETA)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-113",f_espacio="Oficina de Técnicos",f_seccion=(db(db.t_seccion.f_seccion == "Docencia").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-114",f_espacio="Sala de Conferencia (GBBA)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Bioingeniería y Biofísica Aplicada (GBBA)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-115",f_espacio="Laboratorio de Profesores y Tesistas (GBBA)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Bioingeniería y Biofísica Aplicada (GBBA)").select(db.t_seccion.id).first()))
        #db.t_espaciofisico.insert(f_direccion="ELE-116",f_espacio="Laboratorio de Profesores (GBRPS)",Grupo de Biomecánica, f_seccion=(db(db.t_seccion.f_seccion == "Rehabilitación y Procesamiento de Señales (GBRPS)'").select(db.t_seccion.id).first()))
        #db.t_espaciofisico.insert(f_direccion="ELE-117",f_espacio="Laboratorio de Tesistas (GBRPS)",Grupo de Biomecánica, f_seccion=(db(db.t_seccion.f_seccion == "Rehabilitación y Procesamiento de Señales (GBRPS)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-118",f_espacio="Laboratorio de Profesores y Tesistas (GRETA)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Redes Electrónicas y Telemática Aplcada (GRETA)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-119",f_espacio="Laboratorio de Profesores y Tesistas (LISI)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Laboratorio de Investigación en Sistemas de Información (LISI)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-120",f_espacio="Docencia ",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio Universal").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-205",f_espacio="Laboratorio de Profesores y Tesistas (Biomecánica)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Biomecánica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-207",f_espacio="Laboratorio de Profesores y Tesistas (CDCI)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Centro de Diseño de Circuitos Integrados (CDCI)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-208",f_espacio="Docencia",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio Universal").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-209",f_espacio="Docencia",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio Universal").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-214",f_espacio="Docencia",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio Universal").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-215",f_espacio="Docencia",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio Multimedia").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-216",f_espacio="Laboratorio de Profesores",f_seccion=(db(db.t_seccion.f_seccion == "Docencia  (Digitales)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-217",f_espacio="Docencia",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio Multimedia").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-218",f_espacio="Docencia",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio Multimedia").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-219",f_espacio="Laboratorio de Profesores y Tesistas (GEA)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Energía Alternativa (GEA) y Grupo de Acústica y Comunicaciones").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-301",f_espacio="Laboratorio de Profesores y Tesistas (Mecatrónica)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Mecatrónica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-302",f_espacio="Laboratorio de Tesistas (Mecatrónica)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Mecatrónica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-303",f_espacio="Docencia",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio de TV").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-305",f_espacio="Laboratroio de Profesores (GTEL)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Telecomunicaciones (GTEL)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-306",f_espacio="Docencia",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio de Microondas").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-308",f_espacio="Oficina de Tesista (GTEL)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Telecomunicaciones (GTEL)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-310",f_espacio="Cubículo",f_seccion=(db(db.t_seccion.f_seccion == "Docencia").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-313",f_espacio="Laboratorio de Tesistas (GTEL)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Telecomunicaciones (GTEL)").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-315",f_espacio="Docencia",f_seccion=(db(db.t_seccion.f_seccion == "Laboratorio de Telecomunicaciones Básicas").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-328",f_espacio="Laboratorio de Profesores y Tesistas (Mecatrónica)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Mecatrónica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-329",f_espacio="Laboratorio de Profesores y Tesistas (Mecatrónica)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Mecatrónica").select(db.t_seccion.id).first()))
        db.t_espaciofisico.insert(f_direccion="ELE-331",f_espacio="Laboratorio de Profesores y Tesistas (GPS)",f_seccion=(db(db.t_seccion.f_seccion == "Grupo de Procesamiento de Señales (GPS)").select(db.t_seccion.id).first()))
        #borrar los no definidos
        db.executesql("delete from t_espaciofisico where f_seccion is null")
